### ISSUE TITLE
The MAJORA'S MASK（US）can not work on 3DS LL(JP)

### ISSUE THREAD

**Issue by ppp1234z** [smealum/regionthree#11] opened 2015-02-15 03:14 UTC
My system is 9.2.0-20J
When i put it in and start，it success go to gateway web page，and i can see it load the game just for 1second
And then the screen be black and No response

**Comment by dhfromkorea** [comment] 2015-02-15 21:11
same issue here. Any pointers to fix this issue? My system is 9.2.0-20U and I am trying to run a Majora's Mask I purchased in Finland, Europe.

**Comment by m9650827** [comment] 2015-02-15 21:12
## NAVER - http://www.naver.com/

9650827@naver.com 님께 보내신 메일 <Re: [regionthree] The MAJORA'S MASK（US）can not work on 3DS LL(JP) (#11)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---

**Comment by davidstosik** [comment] 2015-02-18 01:08
Yep, Majora's Mask JP does not work on a French 3DS either.
Maybe regionthree does not support "New 3DS"-enhanced games?

Found on @smealum's Twitter feed, if anyone is interested:

> finally had time to actually look and can confirm 100% : MM crashes on regionthree because it can't find the right language files.

([link](https://twitter.com/smealum/status/567200787969748993))

**Comment by smealum** [comment] 2015-02-18 01:10
this is a known issue that has nothing to do with n3ds-enhancements (if you need convincing : just try smash bros on regionthree).
basically the issue is MM tries to load the language files corresponding to the current console and can't find them. because of that, it crashes.
this is not the first time a game exhibits this behavior. unfortunately, it can't be fixed with regionthree.

**Closed as completed by smealum** 2015-02-18 01:10 UTC

**Comment by davidstosik** [comment] 2015-02-18 01:12
Ha! Thanks @smealum! Next thing I did after posting here was to check your Twitter feed, and I had my answer!
